// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3QRWFaPafNXzerQ74uyoWjn2c4bbU3Ck',
    appId: '1:135223368811:web:93b0bfa7829a1562c8652e',
    messagingSenderId: '135223368811',
    projectId: 'bookwise-56ad1',
    authDomain: 'bookwise-56ad1.firebaseapp.com',
    storageBucket: 'bookwise-56ad1.appspot.com',
    measurementId: 'G-5LYQVGZDZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaLUTsVm13zmmiejsMc0UCVAtd65g-F8w',
    appId: '1:135223368811:android:fb4de2d41d71a598c8652e',
    messagingSenderId: '135223368811',
    projectId: 'bookwise-56ad1',
    storageBucket: 'bookwise-56ad1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz1N_HdFGL9OXHQ4DL4K70utQth4jg4bQ',
    appId: '1:135223368811:ios:48335878a32d203bc8652e',
    messagingSenderId: '135223368811',
    projectId: 'bookwise-56ad1',
    storageBucket: 'bookwise-56ad1.appspot.com',
    iosBundleId: 'dev.richhryl.booksphere',
  );
}
